# Generated by Django 6.1 on 2026-09-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
